Draft: Additional support for WebGL2
2gis/2gl pull request #105
Opened 2022-10-11 06:36 UTC by itanka9

2022-10-14 07:44 UTC, Kuznecoff reviewed
ok

2022-10-14 10:50 UTC, Trufi requested changes

2022-10-14 10:50 UTC, Trufi commented on src/Shader.js
> +            console.log(`Error compiling shader, here is code: \n${this._code}`);
А зачем еще консоль лог в дополнение к ошибке?

2022-10-14 10:50 UTC, Trufi commented on src/Vao.js
> +            this._bind(state.gl, ext);
тут какие-то лишние пробелы появились

2022-10-14 12:16 UTC, itanka9 commented on src/Shader.js
> +            console.log(`Error compiling shader, here is code: \n${this._code}`);
У нас была пара кейсов, когда у пользователей валились шейдеры и было очень непонятно, какие именно из сообщения об ошибке.

Валились они и у меня, когда я выполнял отладку. Чтобы понять, что именно валилось я и добавил вывод кода шейдера сюда.

2022-10-14 12:16 UTC, itanka9 commented on src/Vao.js
> +            this._bind(state.gl, ext);
Убрал

2022-10-14 12:59 UTC, itanka9 commented on src/Shader.js
> +            console.log(`Error compiling shader, here is code: \n${this._code}`);
Если весь код шейдера выводить не ок, то могу попробовать выводить только какую-нибудь одну строчку.

2022-10-17 11:51 UTC, Trufi commented on src/Shader.js
> +            console.log(`Error compiling shader, here is code: \n${this._code}`);
А мне казалось, что там понятное сообщение об ошибке бросается. Весь код шейдера, кажется, не ок выводить.

2022-10-17 13:44 UTC, itanka9 commented on src/Shader.js
> +            console.log(`Error compiling shader, here is code: \n${this._code}`);
Сообщения об ошибках получаются понятные, но по ним трудно определить к какому именно шейдеру они относятся. Сейчас выглядит вот так

<img width="1523" alt="Снимок экрана 2022-10-17 в 15 38 47" src="https://user-images.githubusercontent.com/17390418/196192673-602e7ba9-55f0-49e1-bbe8-61e7a4f9254f.png">

А если добавлять строчку с ошибкой, то становится уже понятнее:

<img width="746" alt="Снимок экрана 2022-10-17 в 16 36 12" src="https://user-images.githubusercontent.com/17390418/196193365-192dac5e-807f-453f-aca8-a0b13e7a0ea0.png">
<img width="485" alt="Снимок экрана 2022-10-17 в 16 36 44" src="https://user-images.githubusercontent.com/17390418/196193372-c3623fbb-e4bb-4f2f-b990-ea549d0f6ce3.png">

2022-10-18 03:39 UTC, Trufi commented on src/Shader.js
> +                function (wholeMatch, col, row, message) {
Давай комментов насыпим, что тут происходит, а то ведь никто не поймет :)

2022-10-18 07:40 UTC, itanka9 commented on src/Shader.js
> +                function (wholeMatch, col, row, message) {
Насыпал

2022-10-18 08:15 UTC, Trufi approved these changes

2022-10-18 09:50 UTC, merged