add createShader guard + prettier
2gis/2gl pull request #96
Opened 2021-05-16 07:22 UTC by vitaliy-gis

После создания шейдера добавлена проверка на null и потерю контекста.

2021-05-16 11:08 UTC, Trufi requested changes

2021-05-16 11:08 UTC, Trufi commented on src/Shader.js
> +  constructor(type, code, definitions = []) {
Поправь код стайл во всем файле:
- Отступы должны быть равны 4 пробелам
- Ковычки должны быть одинарными

2021-05-17 06:13 UTC, vitaliy-gis commented on src/Shader.js
> +  constructor(type, code, definitions = []) {
готово

2021-05-17 09:43 UTC, Trufi approved these changes

2021-05-17 19:23 UTC, itanka9 approved these changes

2021-05-18 04:31 UTC, merged